version: "3"
services:
  spring:
    build:
      context: backend
      dockerfile: Dockerfile
    image: showing/backend
    container_name: spring-compose
    ports:
      - 8081:8081
    environment:
      - TZ=Asia/Seoul
    links:
      - mysql-compose
    restart: always
